# NClip Configuration File
# Copy this file to ~/.config/clip/config.toml and customize as needed

[database]
max_entries = 1000

[editor]
text_editor = "nano"
image_editor = "gimp"
image_viewer = "loupe"  # External image viewer for unsupported terminals

# Theme settings - colors can be specified as:
# - ANSI color codes (0-255)
# - Hex codes (#RRGGBB)
# - CSS color names (red, blue, etc.)

[theme.header]
foreground = "13"    # Bright magenta
background = ""
bold = true

[theme.status]
foreground = "8"     # Dark gray
background = ""
bold = false

[theme.search]
foreground = "141"   # Light purple
background = ""
bold = true

[theme.warning]
foreground = "9"     # Bright red
background = ""
bold = true

[theme.selected]
foreground = "15"    # White
background = "55"    # Purple
bold = false

[theme.alternate_background]
foreground = ""
background = "234"   # Very dark gray
bold = false

[theme.normal_background]
foreground = ""
background = ""
bold = false

# Frame settings for dialogs (help, image viewer, text viewer)
[theme.frame.border]
foreground = "39"    # Blue border color
background = ""
bold = false

[theme.frame.background]
foreground = ""
background = "235"   # Dark gray background
bold = false