# NClip Theme Configuration
# This file supports comprehensive theming with inheritance
# Views inherit from [main] theme unless overridden

# Main view theme (serves as default for all views)
[main]

[main.border]
foreground = "8"
background = ""
bold = false

[main.header]
foreground = "8"
background = ""
bold = true

[main.header_separator]
foreground = "8"
background = ""
bold = false

[main.text]
foreground = ""
background = ""
bold = false

[main.highlighted_text]
foreground = "141"
background = ""
bold = true

[main.pinned_indicator]
foreground = "11"  # Yellow
background = ""
bold = true

[main.high_risk_indicator]
foreground = "9"   # Red
background = ""
bold = true

[main.medium_risk_indicator]
foreground = "214"  # Orange
background = ""
bold = true

[main.footer_separator]
foreground = "8"
background = ""
bold = false

[main.footer_key]
foreground = "15"
background = ""
bold = true

[main.footer_action]
foreground = "8"
background = ""
bold = false

[main.footer_divider]
foreground = "8"
background = ""
bold = false

[main.filter_indicator]
foreground = "141"
background = ""
bold = true

[main.normal_background]
foreground = ""
background = ""
bold = false

[main.alternate_background]
foreground = ""
background = ""
bold = false

[main.selected_background]
foreground = "15"
background = "55"
bold = false

[main.global_background]
foreground = ""
background = ""
bold = false

# Text view overrides (optional - inherits from main if not specified)
# [text_view.header]
# foreground = "10"
# background = ""
# bold = true

# [text_view.header_info]
# foreground = "8"
# background = ""
# bold = false

# [text_view.header_risk]
# foreground = "9"
# background = ""
# bold = true

# Image view overrides (optional)
# [image_view.header]
# foreground = "6"
# background = ""
# bold = true

# [image_view.image_info]
# foreground = "6"
# background = ""
# bold = false

# Image unsupported view overrides (optional)
# [image_unsupported.header]
# foreground = "9"
# background = ""
# bold = true

# [image_unsupported.actions]
# foreground = "12"
# background = ""
# bold = false

# Code syntax highlighting theme
[code_highlight]

[code_highlight.keyword]
foreground = "141"
background = ""
bold = true

[code_highlight.string]
foreground = "10"
background = ""
bold = false

[code_highlight.comment]
foreground = "8"
background = ""
bold = false

[code_highlight.number]
foreground = "14"
background = ""
bold = false

[code_highlight.function]
foreground = "12"
background = ""
bold = false

[code_highlight.type]
foreground = "13"
background = ""
bold = false

[code_highlight.operator]
foreground = "9"
background = ""
bold = false

# Scanning warning theme
[scanning_warning.border]
foreground = "9"
background = ""
bold = true

[scanning_warning.title]
foreground = "9"
background = ""
bold = true

[scanning_warning.body]
foreground = "7"
background = ""
bold = false

[scanning_warning.prompt]
foreground = "8"
background = ""
bold = false

# Legacy theme fields (kept for backward compatibility)
[header]
foreground = "8"
background = ""
bold = true

[status]
foreground = "8"
background = ""
bold = false

[search]
foreground = "141"
background = ""
bold = true

[warning]
foreground = "9"
background = ""
bold = true

[selected]
foreground = "15"
background = "55"
bold = false

[alternate_background]
foreground = ""
background = ""
bold = false

[normal_background]
foreground = ""
background = ""
bold = false

[frame.border]
foreground = "8"
background = ""
bold = false

[frame.background]
foreground = ""
background = ""
bold = false